subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/freqhopping/

obj-$(CONFIG_MTK_FREQ_HOPPING) := mt_freqhopping_drv.o

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/freqhopping/$(MTK_PLATFORM)/
obj-y += $(MTK_PLATFORM)/
