# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2019 MediaTek Inc.

# drivers/image/jpeg/Makefile

# use common driver
ifneq (,$(filter $(CONFIG_MTK_PLATFORM), "mt6757" "mt6799" "kiboplus" "mt6759" "mt6763" "mt6758" "mt6739" "mt6765" "mt6761" "mt8168"))
  # new chip use v2 driver
  obj-y += v2/
endif
# EOF
